const moveGroups = [
    {
        name: "Solo Moves",
        moves: [
            { name: "Angle Back", semi: false, date: null },
            { name: "Angle Braid", semi: false, date: null },
            { name: "Angle Slave", semi: false, date: null },
            { name: "Angle Suzy", semi: false, date: null },
            { name: "Basic", semi: false, date: null },
            { name: "Braid", semi: false, date: null },
            { name: "Cha Cha Cha Basic", semi: false, date: null },
            { name: "Cord Beat Crossover", semi: false, date: null },
            { name: "Cord Beat Suzy", semi: false, date: null },
            { name: "Cutaway", semi: false, date: null },
            { name: "Double Four Tap V", semi: false, date: null },
            { name: "Double Hunts Point", semi: false, date: null },
            { name: "Double Left Flare", semi: false, date: null },
            { name: "Double Suzy Plus", semi: false, date: null },
            { name: "Double Tap Crossover Slide", semi: false, date: null },
            { name: "Double Tap Crossover Slide Plus", semi: false, date: null },
            { name: "Double Tap Suzy Q Cross Slide", semi: false, date: null },
            { name: "Downtown", semi: true, date: null },
            { name: "Downtown with a Turn", semi: false, date: null },
            { name: "Forward Crossover", semi: false, date: null },
            { name: "Forward Crossover Suzy Q", semi: false, date: null },
            { name: "Forward Crossover Left Front Double Cross Suzy Q", semi: false, date: null },
            { name: "Four Corners", semi: false, date: null },
            { name: "Four Tap V", semi: false, date: null },
            { name: "Front Double Basic", semi: false, date: null },
            { name: "Hook Flick", semi: false, date: null },
            { name: "Hook Step", semi: true, date: null },
            { name: "Hot Toe", semi: true, date: null },
            { name: "Hot Toe Suzy", semi: false, date: null },
            { name: "Hot Toe Combo", semi: false, date: null },
            { name: "Hunts Point", semi: false, date: null },
            { name: "Inverted Suzy Plus", semi: false, date: null },
            { name: "Lateral Cutaway", semi: false, date: null },
            { name: "Left Front Double Cross", semi: false, date: null },
            { name: "Left Flare", semi: false, date: null },
            { name: "Left into Right Front Double Cross", semi: false, date: null },
            { name: "Outside Cutaway", semi: false, date: null },
            { name: "Quadruple Suzy Plus", semi: false, date: null },
            { name: "Reverse Crossover Suzy Q", semi: false, date: null },
            { name: "Right Front Double Cross", semi: false, date: null },
            { name: "Semi Circle", semi: false, date: null },
            { name: "Side Basic", semi: true, date: null },
            { name: "Side Basic Plus", semi: false, date: null },
            { name: "Side Slide", semi: false, date: null },
            { name: "Side Triplet", semi: false, date: null },
            { name: "Single Tap Crossover Slide", semi: false, date: null },
            { name: "Single Tap Crossover Slide Plus", semi: false, date: null },
            { name: "Slave", semi: false, date: null },
            { name: "Suzy Cross Suzy", semi: false, date: null },
            { name: "Suzy Q", semi: true, date: null },
            { name: "Suzy Q Hook Combo", semi: true, date: null },
            { name: "Suzy Q Hook Combo Plus", semi: true, date: null },
            { name: "Suzy Q Plus", semi: true, date: null },
            { name: "Symmetrical Angle Suzy", semi: false, date: null },
            { name: "Symmetrical Angle Back", semi: false, date: null },
            { name: "Syncopated Front Double Cross", semi: false, date: null },
            { name: "Syncopated Front Double Cross Turn Combo", semi: false, date: null },
            { name: "Triple Four Tap V", semi: false, date: null },
            { name: "Triple Suzy Plus", semi: false, date: null },
            { name: "Turn Combo", semi: false, date: null },
            { name: "Ultra Combo", semi: false, date: null }
        ]
    },
    {
        name: "Women's Partnerwork",
        moves: [
            { name: "Broken Left Turn", semi: false, date: null },
            { name: "Copa", semi: false, date: null },
            { name: "Cross Body Lead", semi: false, date: null },
            { name: "Inside Left", semi: false, date: null },
            { name: "Right Turn", semi: false, date: null }
        ]
    },
    {
        name: "Men's Partnerwork",
        moves: [
            { name: "About Face Right Turn", semi: false, date: null },
            { name: "Axle Right / Axle Left", semi: false, date: null },
            { name: "Back Charge", semi: false, date: null },
            { name: "Cross Body Lead", semi: false, date: null },
            { name: "Full Axle Right Turn", semi: false, date: null },
            { name: "Half Right Half Left", semi: false, date: null },
            { name: "Half Left Back Charge", semi: false, date: null },
            { name: "Half Right Back Charge", semi: false, date: null },
            { name: "Left Spot Right Turn (Axel Left)", semi: false, date: null },
            { name: "Side Charge", semi: false, date: null },
            { name: "Walk Around Left Turn", semi: false, date: null },
            { name: "3 O'Clock Right Turn", semi: false, date: null }
        ]
    }
];
